### ISSUE TITLE
a couple of entries with no DOI

### ISSUE THREAD

**Issue by cpmpercussion** [NIME-conference/NIME-bibliography#17]
```
No DOI for: Baldwin2016
No DOI for: Chang2016
No DOI for: Long2016
No DOI for: McPherson2016

No DOI for: GreshamLancaster2009
```

**Comment by alexarje** [comment]
Have fixed GreshamLancaster2009. The others appear to be missing Zenodo entries, so they will need to be uploaded there first: 

Baldwin2016
Chang2016
Long2016
McPherson2016

**Comment by alexarje** [comment]
Have uploaded these to Zenodo now, and added DOIs to the files.
