### ISSUE TITLE
Please Consider Adding IDs to <li> Items in The Archives

### ISSUE THREAD

**Issue by code-warrior** [NIME-conference/NIME-bibliography#4]
Each entry in the archive uses a `<li>` element, but there’s no way to distinguish, for the sake of a link, one entry from another. For example, if I wanted to link to my paper, *The MIDI Pick*, I can only link to the citation at the bottom of the entry: [`http://www.nime.org/archives/#papercite_423`](http://www.nime.org/archives/#papercite_423).

With an ID in the `<li>` element, I could like to the beginning of the entry instead of the citation.

**Comment by alexarje** [comment]
Sorry for having not attended to this issue earlier on. Would you have a suggestion for how to do this in the code of the papercite plugin that we use? https://github.com/bpiwowar/papercite

**Comment by cpmpercussion** [comment]
this is something for the present website repo and will be fixed in upcoming updates.
