### ISSUE TITLE
Paper "A Self-Organizing Gesture Map for a Voice-Controlled Instrument Interface" missing last page

### ISSUE THREAD

**Issue by DocSunset** [NIME-conference/NIME-bibliography#58]
Hi there.

Not sure if this is the appropriate place to report this issue, but nevertheless I thought someone should know: the pdf associated with the paper cited below is missing the last page (page 512). 

Stefano Fasciani and Lonce Wyse. 2013. A Self-Organizing Gesture Map for a Voice-Controlled Instrument Interface. Proceedings of the International Conference on New Interfaces for Musical Expression, Graduate School of Culture Technology, KAIST, pp. 507–512.

**Comment by alexarje** [comment]
Yes, indeed. Thanks for spotting this. I found a camera-ready version of the file. This one does not have page numbering but otherwise seems to be fine, so have replaced it with that one.
