### ISSUE TITLE
Add checking of special characters 

### ISSUE THREAD

**Issue by alexarje** [NIME-conference/NIME-bibliography#60]
When [uploading to Zenodo](https://github.com/NIME-conference/Zenodo-upload), special characters cause problems. It would be good to add the conversion of special characters to a script.

**Comment by cpmpercussion** [comment]
working on this one now.

The special character treatment is a mix, some procs were provided with LaTeX special characters, some with UTF8.

Honestly I think UTF8 should be preferred and LaTeX special characters deprecated as the latter cause problems down the pipeline (e.g., in the Zenodo upload above) and tend to get broken. 

We don't have a "latex test" on the proc (maybe we should!!) that would identify actually broken latex code in the titles/author/abstracts anyway.

I'm currently adding code to convert to UTF8 for (at least) the collated CSV/JSON/YAML outputs, and maybe BibTex as well.

**Comment by cpmpercussion** [comment]
0f32b55 now mostly removes special characters from CSV, JSON and YAML output and these should be preferred for alternate uses (outside of making latex documents)
