### ISSUE TITLE
How to contribute to nime23.bib?

### ISSUE THREAD

**Issue by piaoziyue** [NIME-conference/NIME-bibliography#70]
Hi NIME community,

For my paper reading purpose, I summarized a nime2023.bib file with a similar format to your nine20XX.bib. I'm not sure if you've already finished the nime2023.bib. If not, can I upload my nime2023 bibliography to /paper-proceeding?

Thanks,
Ziyue Piao
McGill University

**Comment by stefanofasciani** [comment]
I am not sure about who is in charge of the nime2023.bib and what is the current status, but it would be great to have the the 2023 papers in the proceedings page ASAP.
@piaoziyue if you do not mind, can you share the file you have made? I would like to use it (perhaps you can just attach it to a comment below).

Stefano

**Comment by piaoziyue** [comment]
Hi Stefano,

Here it is!
[nime2023.bib.zip](https://github.com/NIME-conference/NIME-bibliography/files/13717499/nime2023.bib.zip)

Thanks
Monica

**Comment by stefanofasciani** [comment]
great, thanks!

**Comment by stefanofasciani** [comment]
[nime2023.bib.zip](https://github.com/NIME-conference/NIME-bibliography/files/13742138/nime2023.bib.zip)

Attached a minor improvement (fixed an error on author's name, and updated the URL to a Googl Drive path allowing direct download).

**Comment by cpmpercussion** [comment]
Thanks for pitching in folks, the 2023 bib is now in place with further information added from the organisers of NIME2023.
