### ISSUE TITLE
Wrong citation

### ISSUE THREAD

**Issue by musicinmotion-dev** [NIME-conference/NIME-bibliography#76]
For some reason I'm displayed twice as author for my article this year:

Robert Ek, and Robert Ek.

Please erase me as co-author since I'm first author, the article is number 24, Playing with resistance

https://nime.org/proc/nime2024_24/index.html

**Comment by stefanofasciani** [comment]
fixed in [e12e105](https://github.com/NIME-conference/NIME-bibliography/commit/e12e1057b4645d568dc07d5d8b597293ed95d3f0)
