### ISSUE TITLE
The order of the authors everywhere on the page is not as given in the paper

### ISSUE THREAD

**Issue by belausabaev** [NIME-conference/NIME-bibliography#77]

**Comment by stefanofasciani** [comment]
Can you please post the URL of the paper with wrong author order?
This is paper 77 and the order appears to be correct https://nime.org/proc/nime2024_77/index.html

**Comment by stefanofasciani** [comment]
Please open a new issue posting posting the URL of the paper with wrong author order.
This is paper 77 (from 2024) and the order appears to be correct https://nime.org/proc/nime2024_77/index.html

**Comment by belausabaev** [comment]
Hi,

sorry, it is about the publication 75, somehow the issue reply got assigned
to the wrong publication number.

I have opened a new issue referencing the correct publication number.

All the best,

Bela

Am Mi., 16. Okt. 2024 um 09:52 Uhr schrieb Stefano Fasciani <
***@***.***>:

**Comment by belausabaev** [comment]
We have addressed the mistake via mail before the conference, but it hasn't
been fixed.


Bela Usabaev ***@***.***> schrieb am Mi., 16. Okt. 2024, 10:58:
